### PR TITLE
[New UI] Fix functional and cosmetic issues pre-release

### LINKED ISSUE #21: Option Size input reflects different decimal points
Inputting 2 ETH option size, results in minted option size 0.002 ETH 
image

Inputting 1 ETH option size, results in minted option size 0.001 ETH 
image

### LINKED ISSUE #27: If user changes address in MetaMask, application shouldn't require refresh
If user changes address in MetaMask, application shouldn't require refresh to display correct data.

I suggest you tap into `accounts-changed` event of `district-ui-web3-accounts`
https://github.com/district0x/district-ui-web3-accounts#accounts-changed

### PR DESCRIPTION
**Pull request by st4cks1defl0w**
Fixing account reload issue (main one), option size output issue in tables and about-section hide-on-click-(outside)

### CODE REVIEW

File: src/district_hegex/ui/core.cljs [hunk 1]
```diff
@@ -105,3 +106,49 @@
...
+
+    (js/console.log "config:" (clj->js full-config))
+    (-> (mount/with-args full-config)
+      (mount/start))
+    (re-frame/dispatch [::init])))
+
+
+(re-frame/reg-event-fx
+  ::listen-to-account-change
+  (fn []
```
Comment (st4cks1defl0w) [inline src/district_hegex/ui/core.cljs:135]: It appears like `::web3-accounts-events` lib listeners that detect account change are incompatible with new Metamask. I quickly checked out memefactory since it relies on the same listeners, it looks like it's not detecting account change there too (though address change is reflected in UI, I think this is because it uses a separate district0x module that outputs active account).
Hence this barebones-js listener workaround
